name: Build pages

on:
  push:
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: pick a random MOTD
      run: |
        export motd="$(ls motd_glyphs | shuf | head -n 1)"
        export charactername=$(echo "$motd" | sed 's/_.*//' | sed 's/.*/\u&/')
        export msg="$(shuf motd_texts.txt | head -n 1)"
        cp motd_glyphs/"$motd" motd
        echo -e "\n$charactername's message of the day: \"$msg\"" >> motd
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: .
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4