# File: .github/workflows/refresh.yml
name: Periodic Rebuild

on:
  workflow_dispatch:
  schedule:
    - cron:  '20 2 * * *' # Runs every day at 2:20A

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub pages rebuild
        run: |
          curl -L --fail --request POST \          
          --header "Authorization: Bearer $USER_TOKEN" \
          --url https://api.github.com/repos/${{ github.repository }}/actions/workflows/build-pages/dispatches \
          -d '{"ref":"master"}'
        env:
          # You must create a personal token with repo access as GitHub does
          # not yet support server-to-server page builds.
          USER_TOKEN: ${{ secrets.USER_TOKEN }}